payloads ={
    "testBingol": {
        "aksiyonId": 200,
        "mhrsIlId": 12,
        "mhrsKlinikId": 157,
        "mhrsKurumId": 5116,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "paluDis": {
        "aksiyonId": 200,
        "mhrsIlId": 23,
        "mhrsIlceId": 1566,
        "mhrsKlinikId": 198,
        "baslangicZamani": "2025-04-08 12:54:29",
        "bitisZamani": "2025-04-12 18:54:29",
        "mhrsKurumId": 6495,
        "mhrsHekimId": -1,
        "muayeneYeriId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": [1]
    },
    "bursaKbb": {
        "aksiyonId": 200,
        "mhrsIlId": 16,
        "mhrsIlceId": 1832,
        "mhrsKlinikId": 165,
        "baslangicZamani": "2025-04-15 12:54:29",
        "bitisZamani": "2025-04-12 17:54:29",
        "mhrsKurumId": 177154,
        "mhrsHekimId": -1,
        "muayeneYeriId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": [1]
    },
    "kovancilarKBB": {
        "aksiyonId": 200,
        "mhrsIlId": 23,
        "mhrsIlceId": 1820,
        "mhrsKlinikId": 165,
        "baslangicZamani": "2025-04-11 12:54:29",
        "bitisZamani": "2025-04-12 18:54:29",
        "mhrsKurumId": 8488,
        "mhrsHekimId": -1,
        "muayeneYeriId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "bingolDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 12,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 5116,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "fethiSekinDahiliye": {
        "aksiyonId": 200,
        "mhrsIlId": 23,
        "mhrsIlceId": 1298,
        "mhrsKlinikId": 157,
        "mhrsKurumId": 656194,
        "tumRandevular": False,
        "ekRandevu": True,
        "baslangicZamani": "2025-04-21 09:20:29",
        "bitisZamani": "2025-04-21 13:54:29",
        "randevuZamaniList": [1],
    },
    "dahiliyeNumuneHast": {
        "aksiyonId": 200,
        "mhrsHekimId": 48438,
        "mhrsIlId": 342,
        "mhrsIlceId": 1708,
        "mhrsKlinikId": 157,
        "mhrsKurumId": 3305,
        "muayeneYeriId": 7071334,
        "tumRandevular": False,
        "ekRandevu": True,
    },
    "testElazig1": {
        "aksiyonId": 200,
        "mhrsIlId": 23,
        "mhrsKlinikId": 196,
        "mhrsKurumId": 656194,
        "ekRandevu": True,
        "randevuZamaniList": [],
    },
    "ElazigFethisekin": {
        "aksiyonId": 200,
        "mhrsIlId": 23,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 656194,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "ElazigFethisekinEriskin": {
        "aksiyonId": 200,
        "mhrsIlId": 23,
        "mhrsKlinikId": 210,
        "mhrsKurumId": 656194,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },

    "sultanGaziFatihHasekiEAHCocukPsikiyatr": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2055,
        "mhrsKlinikId": 134,
        "mhrsKurumId": 5796,
        "muayeneYeriId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "esenyurtNecmiKadıogluDevhast": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2053,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 223531,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "bakirkoySadiKonukEAH": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1166,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 3457,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "bagcilarEAH": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2004,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 183567,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "bagcilarEAHGoz": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2004,
        "mhrsKlinikId": 151,
        "mhrsKurumId": 183567,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "baltaLimaniKemikHastalıklariEAH": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1604,
        "mhrsKlinikId": 137,
        "mhrsKurumId": 3359,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "pendikEAR": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1835,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 395236,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "hamidiyeEftalEarCozger": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1604,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 3324,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "hamidiyeEftalEarEkHizmetÇocukPsikiyatrisi": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1604,
        "mhrsKlinikId": 181,
        "mhrsKurumId": 5789,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sisliHamidiyeEftalCocukPsikiyatrisiMeryemTan": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1663,
        "mhrsKlinikId": 134,
        "mhrsHekimId": 42497,
        "mhrsKurumId": 3324,
        "muayeneYeriId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sisliHamidiyeEftalCocukPsikiyatrisiMeryemTan2": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1604,
        "mhrsKlinikId": 134,
        "mhrsHekimId": 42497,
        "mhrsKurumId": 5789,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "BingolSehirHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 12,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 5116,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "cizreDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 73,
        "mhrsIlceId": 1223,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 174,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "cizreDevletHastanesiEriskin": {
        "aksiyonId": 200,
        "mhrsIlId": 73,
        "mhrsIlceId": 1223,
        "mhrsKlinikId": 210,
        "mhrsKurumId": 174,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sirnakDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 73,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 166,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sirnakDevletHastanesiEriskin": {
        "aksiyonId": 200,
        "mhrsIlId": 73,
        "mhrsKlinikId": 210,
        "mhrsKurumId": 166,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "MaltepePendikDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 2012,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 707143,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "kosuyoluEAH": {
        "aksiyonId": 200,
        "baslangicZamani": "2025-05-07 23:16:33",
        "bitisZamani": "2025-05-09 17:16:43",
        "mhrsIlId": 342,
        "mhrsIlceId": 1449,
        "mhrsKlinikId": 163,
        "mhrsKurumId": 3401,
        "randevuZamaniList": ["1","2"],
        "ekRandevu": True,
        "tumRandevular": False
    },
    "silivriCildiye": {
        "aksiyonId": 200,
        "baslangicZamani": "2025-05-10 23:16:33",
        "bitisZamani": "2025-05-15 17:16:43",
        "mhrsIlId": 341,
        "mhrsIlceId": 1622,
        "mhrsKlinikId": 136,
        "mhrsKurumId": 3294,
        "randevuZamaniList": ["1", "2"],
        "ekRandevu": True,
        "tumRandevular": False
    },
    "kadikoySuleymanYalcinDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1421,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 177296,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "uskudarSultanAbdulhamidhanHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1708,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 887161,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
        },
    "CekmekoySancaktepeIlhanVarankEAH": { #İSTANBUL-(ANADOLU)-SANCAKTEPE ŞEHİT PROF.DR.İLHAN VARANK EĞİTİM VE ARAŞTIRMA HASTANESİ
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 2052,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 631921,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "EsenyurtNecmiKadiogluDevletHastanesi": { #İSTANBUL- (AVRUPA)- ESENYURT NECMİ KADIOĞLU DEVLET HASTANESİ
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2053,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 223531,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sultangaziHasekiEAH": { #daha önce alabildi
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2055,
        "mhrsKlinikId": 211,
        "mhrsKurumId": -1, #5796 
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sultanGaziFatihHasekiEAH": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2055,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 3384,
        "muayeneYeriId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sisliCemilTasciogluSehirHast": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1663,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 177300,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sisliCemilTasciogluSehirHastEriskinHasta": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1663,
        "mhrsKlinikId": 210,
        "mhrsKurumId": 177300,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "gaziosmanpasaEAHEriskinHasta": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1336,
        "mhrsKlinikId": 210,
        "mhrsKurumId": 3407,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "basaksehirDevletHast": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2050,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 187596,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "basaksehirCamveSakuraSehirHastEriskin": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2050,
        "mhrsKlinikId": 210,
        "mhrsKurumId": 27911,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "basaksehirCamveSakuraSehirHastCocukNorolojisi": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2050,
        "mhrsKlinikId": 129,
        "mhrsKurumId": 27911,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "basaksehirCamveSakuraSehirHast": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2050,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 27911,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "basaksehirCamveSakuraSehirHastRomatoloji": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2050,
        "mhrsKlinikId": 180,
        "mhrsKurumId": 27911,
        "mhrsHekimId": 134798,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "buyukCekmeceMimarSinanDevletHast": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1782,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 642968,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "kucukCekmeceKanuniSultanSuleymanEAH": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1823,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 426876,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "KanuniSultanSuleymanEAHFizikselTıpVeRHBT": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1823,
        "mhrsKlinikId": 142,
        "mhrsKurumId": 426876,
        "mhrsHekimId": 495971,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },

    "HaydarpaşaNumuneHastCildiye": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1708,
        "mhrsKlinikId": 136,
        "baslangicZamani": "2025-02-11 15:58:10",
        "bitisZamani": "2025-02-12 15:58:12",
        "mhrsKurumId": 3305,
        "mhrsHekimId": -1,
        "muayeneYeriId": 10149749,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },

    "HaydarpaşaNumuneHastGoz": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1708,
        "mhrsKlinikId": 151,
        "baslangicZamani": "2025-03-12 08:03:00",
        "bitisZamani": "2025-03-12 15:03:04",
        "mhrsKurumId": 3305,
        "mhrsHekimId": -1,
        "muayeneYeriId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": [1]
    },
    "HaydarpasaNumuneHastDahiliyeYeldegirmeni": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1708,
        "mhrsKlinikId": 157,
        "baslangicZamani": "2025-02-28 08:00:21",
        "bitisZamani": "2025-02-28 08:30:21",
        "mhrsKurumId": 188020,
        "mhrsHekimId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": [1]
    },
    "HaydarpaşaNumuneHastCildiye2": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1708,
        "mhrsKlinikId": 136,
        "baslangicZamani": "2025-02-11 15:58:10",
        "bitisZamani": "2025-02-12 15:58:12",
        "mhrsKurumId": 3305,
        "mhrsHekimId": -1,
        "muayeneYeriId": 10045300,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "HaydarpaşaNumuneHastKBB": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": 1708,
        "mhrsKlinikId": 165,
        "baslangicZamani": "2025-02-11 14:20:06",
        "bitisZamani": "2025-02-12 10:20:13",
        "mhrsKurumId": 3305,
        "mhrsHekimId": -1,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "avcilarMuratKolukDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 2003,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 793110,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "gaziosmanpasaEAH": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1336,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 3407,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "gaziosmanpasaEAHCocukErgenPsikiyatr": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1336,
        "mhrsKlinikId": 134,
        "mhrsKurumId": 3407,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "EyupDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1325,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 177295,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "tekirdagCerkezkoy": {
        "aksiyonId": 200,
        "mhrsIlId": 341,
        "mhrsIlceId": 1250,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 14617,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "KmarasAfsinDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 46,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 1953,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "KmarasElbistanDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 46,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 1933,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "KmarasNecipFazılDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 46,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 731072,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "KmarasPazarcikDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 46,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 1915,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "EskisehirSehirHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 26,
        "mhrsIlceId": -1,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 656195,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "EskisehirYunusEmreDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 26,
        "mhrsIlceId": -1,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 177230,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "EdirneSultanMuratDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 22,
        "mhrsIlceId": -1,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 4341,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "OsmaniyeDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 80,
        "mhrsIlceId": -1,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 6230,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "OsmaniyeKadirliDevletHastanesi": {
        "aksiyonId": 200,
        "mhrsIlId": 80,
        "mhrsIlceId": -1,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 6275,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "goztepeSuleymanYalcin": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": -1,
        "mhrsKlinikId": 136,
        "mhrsKurumId": 177296,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "sultanAbdulhamithanOncelik": {
        "aksiyonId": 200,
        "mhrsIlId": 342,
        "mhrsIlceId": -1,
        "mhrsKlinikId": 136,
        "mhrsKurumId": 887161,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    },
    "TrabzonKanuniEAH": { #TRABZON KANUNİ EĞİTİM VE ARAŞTIRMA HASTANESİ
        "aksiyonId": 200,
        "mhrsIlId": 61,
        "mhrsIlceId": -1,
        "mhrsKlinikId": 211,
        "mhrsKurumId": 463372,
        "tumRandevular": False,
        "ekRandevu": True,
        "randevuZamaniList": []
    }
}
def get_hospital_payload(payload_name):
    return payloads.get(payload_name, {})